### ISSUE TITLE
MMDVM Unknown

### ISSUE THREAD

**Issue by es2ast** [nano-mmdvm/Duplex_hotSPOT#7]
Brandmeister dont show correct hardware info.
Hardware | Unknown (MMDVM)
![rep-model-unknown](https://user-images.githubusercontent.com/38312339/38665604-78692b80-3e45-11e8-964d-2cd70c95d9ba.png)

**Comment by M6NBP** [comment]
I believe you will need to ask BM to add the board to the system

**Comment by es2ast** [comment]
Looks like MMDVMHost dont know such hardware in duplex mode.
![2018-05-06-173636_3328x1152_scrot](https://user-images.githubusercontent.com/38312339/39674471-2004b9e6-5155-11e8-9550-9078bc2cbfe2.png)

**Comment by es2ast** [comment]
How to name nano_hotSPOT duplex version? MMDVM_Duplex_Nano_hotSPOT, MMDVM_Nano_Duplex_hotSPOT ...?

Temporary MMDVMHost fix:
open DMRNetwork.cpp file
add this after line 546
```
case HWT_NANO_HOTSPOT:
	software = "MMDVM_Nano_hotSPOT";
	break;
```

**Comment by bi7jta** [comment]
Great,TKS  es2ast
@VR2VYE
